### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by n3oney** [arkenthera/electron-vibrancy#29]
When i try to use it, i get this error: 
```
Uncaught (in promise) Error: %1 is not a valid Win32 application.
\\?\C:\Users\neoney\AppData\Roaming\BetterDiscord\plugins\node_modules\electron-vibrancy\build\Debug\Vibrancy.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings 
```
I have used NVM to change the node version to 11.6.0 32-bit, no success.

**Comment by n3oney** [comment]
Closing, just had to compile it for 32 bit (remember to use ia32, not x32 nor x86!)
