### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by shen-lan** [arkenthera/electron-vibrancy#30]
```
MSBUILD : error MSB3428: δ▒ܼ▒▒▒ Visual C++ ▒▒▒▒▒VCBuild.exe▒▒▒▒Ҫ▒▒▒▒▒▒▒▒⣬1) ▒▒װ .NET Framework 2.0 SDK▒▒2) ▒▒װ Microsoft Visual Studio 2005▒▒▒▒ 3) ▒▒▒▒▒▒▒▒▒▒▒▒װ▒▒▒▒▒▒▒▒λ▒ã▒▒뽫▒▒λ▒▒▒▒ӵ▒ϵͳ·▒▒▒С▒ [C:\Users\***\AppData\Roaming\npm\node_modules\electron-vibrancy\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

**Comment by arxanter** [comment]
Hello. Same problem. Any news?

**Comment by NetOpWibby** [comment]
Doesn't work on macOS Catalina. Womp.

EDIT: This repo isn't necessary anymore. `vibrancy: "light"` works inside `new BrowserWindow`.
