### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by jackcrane** [arkenthera/electron-vibrancy#32]
I am attempting to install electron-vibrancy, and when I build, I am getting the following:

```
C:\electron\quick start\electron-vibrancy>npm install

> electron-vibrancy@0.1.3 install C:\electron\quick start\electron-vibrancy
> node-gyp rebuild


C:\electron\quick start\electron-vibrancy>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Vibrancy.cc
  vibrancy_win.cc
  Init.cc
  win_delay_load_hook.cc
c:\electron\quick start\electron-vibrancy\src\vibrancy.cc(86): error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments [C:\electron\quick start\electron-vibrancy\build\Vibrancy.vcxproj]
c:\electron\quick start\electron-vibrancy\src\vibrancy_win.cc(57): warning C4996: 'GetVersionExA': was declared deprecated [C:\electron\quick start\electron-vibrancy\build\Vibrancy.vcxproj]
  c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\sysinfoapi.h(378): note: see declaration of 'GetVersionExA'
c:\electron\quick start\electron-vibrancy\src\vibrancy_win.cc(112): warning C4312: 'type cast': conversion from 'uint32_t' to 'HWND' of greater size [C:\electron\quick start\electron-vibrancy\build\Vibrancy.vcxproj]
c:\electron\quick start\electron-vibrancy\src\vibrancy_win.cc(120): warning C4312: 'type cast': conversion from 'uint32_t' to 'HWND' of greater size [C:\electron\quick start\electron-vibrancy\build\Vibrancy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\electron\quick start\electron-vibrancy
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vibrancy@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-vibrancy@0.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jenks\AppData\Roaming\npm-cache\_logs\2019-12-03T18_40_46_226Z-debug.log
```

Please help!

**Comment by smultar** [comment]
Has anyone found the solution to this install problem as well?

**Comment by mazzadomenico** [comment]
I have installed "Python 3.9" development kit from Windows Store and installed node-gyp with npm. So i fixed this issue.

**Comment by DrunkWinter** [comment]
Fixed here https://github.com/DrunkWinter/electron-vibrancy

**Comment by im-nassinger** [comment]
I'm getting the same error

**Comment by liuyike98** [comment]
the same problem, i don't know what has happend!
